apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5015
        env:
        - name: PORT
          value: "5015"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: appointment-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: appointment-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: appointment-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: appointment-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: appointment-secrets
              key: CLOUDINARY_API_SECRET
        - name: TELEMEDICINE_SERVICE_URL
          value: "http://telemedicine-service:5018"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
  - port: 5015
    targetPort: 5015
  type: ClusterIP