---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine
  template:
    metadata:
      labels:
        app: telemedicine
    spec:
      containers:
      - name: telemedicine-container
        image: healthcare-microservices-telemedicine-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5018
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: JWT_SECRET
        - name: APPOINTMENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: APPOINTMENT_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: NOTIFICATION_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: PAYMENT_SERVICE_URL
        - name: DOCTOR_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: DOCTOR_SERVICE_URL
        - name: PATIENT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: PATIENT_SERVICE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  type: ClusterIP
  selector:
    app: telemedicine
  ports:
  - protocol: TCP
    port: 5018
    targetPort: 5018
